version: '3.8'
services:
  postgredb:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  app:
    image: htrgl/credit-system-api
    container_name: api
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      NODE_ENV: 'production'
      DB_HOST: 'postgredb'
      DB_PORT: 5432
      DB_NAME: 'postgres'
      DB_USERNAME: 'postgres'
      DB_PASS: 'postgres'
      TEST_DB_HOST: 'postgredb'
      TEST_DB_PORT: 5432
      TEST_DB_NAME: 'postgres'
      TEST_DB_USERNAME: 'postgres'
      TEST_DB_PASS: 'postgres'
    depends_on:
      - postgredb
