version: '3.8'
services:
  postgredb:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
  app:
    image: htrgl/football-fixture-system
    container_name: api
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      NODE_ENV: 'production'
      DB_HOST: 'localhost'
      DB_PORT: 5432
      DB_NAME: 'postgres'
      DB_USERNAME: 'postgres'
      DB_PASS: '12345'
      DEV_DB_HOST: 'localhost'
      DEV_DB_PORT: 5432
      DEV_DB_NAME: 'postgres_test'
      DEV_DB_USERNAME: 'postgres'
      DEV_DB_PASS: 'securepassword'
    depends_on:
      - postgredb
